export const restraunt_IMG_CDN =
  "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";

export const FETCH_RESTRAUNTMENU_API_URL =
  "https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=28.6313407&lng=77.2198645&restaurantId=";

export const RestrauntData = [
  {
    type: "restaurant",
    info: {
      type: "F",
      id: "92029",
      name: "Lazeez Kebab & Curries",
      uuid: "bfefe620-f296-4e7d-aa30-499bf7084b37",
      city: "4",
      area: "Rajinder Nagar",
      totalRatingsString: "",
      cloudinaryImageId: "uyptjsvthfqfepoymf0w",
      cuisines: ["North Indian", "Chinese", "Kebabs"],
      tags: [],
      costForTwo: 40000,
      costForTwoString: "₹400 FOR TWO",
      deliveryTime: 23,
      minDeliveryTime: 23,
      maxDeliveryTime: 23,
      slaString: "23 MINS",
      lastMileTravel: 0,
      slugs: {
        restaurant: "lazeez-kebab-curries-old-rajender-nagar-karol-bagh",
        city: "Delhi",
      },
      cityState: "4",
      address: "",
      locality: "3rd Block",
      parentId: 15617,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfoV2: {
        header: "",
        shortDescriptionList: [],
        descriptionList: [],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "BASE_DISTANCE",
            fee: 4400,
            message: "",
          },
          {
            name: "BASE_TIME",
            fee: 0,
            message: "",
          },
          {
            name: "ANCILLARY_SURGE_FEE",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 4400,
        message: "",
        title: "Delivery Charge",
        amount: "4400",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID:
        "cid=7586127~p=1~eid=00000189-8df9-381d-0462-7618000d014b~srvts=1690304067613~80462",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "4.9 kms",
      hasSurge: false,
      cta: {
        link: "swiggy://menu?restaurant_id=92029&source=collection&query=Momos",
        type: "DEEPLINK",
        text: "RESTAURANT_MENU",
      },
      sla: {
        restaurantId: "",
        deliveryTime: 23,
        minDeliveryTime: 23,
        maxDeliveryTime: 23,
        lastMileTravel: 0,
        lastMileDistance: 4.9,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "4.0",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    info: {
      type: "F",
      id: "592569",
      name: "Chinese So Yum",
      uuid: "c68517eb-ea44-4d65-a860-79003736f202",
      city: "4",
      area: "Defence Colony",
      totalRatingsString: "",
      cloudinaryImageId: "wtyullwntinxwkrgr1ae",
      cuisines: ["Chinese", "Pan-Asian", "Snacks"],
      tags: [],
      costForTwo: 25000,
      costForTwoString: "₹250 FOR TWO",
      deliveryTime: 32,
      minDeliveryTime: 32,
      maxDeliveryTime: 32,
      slaString: "32 MINS",
      lastMileTravel: 0,
      slugs: {
        restaurant: "chinese-so-yum-lajpat-nagar-lajpat-nagar",
        city: "Delhi",
      },
      cityState: "4",
      address: "",
      locality: "Lajpat Nagar",
      parentId: 354318,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfoV2: {
        header: "",
        shortDescriptionList: [],
        descriptionList: [],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "BASE_DISTANCE",
            fee: 6800,
            message: "",
          },
          {
            name: "BASE_TIME",
            fee: 0,
            message: "",
          },
          {
            name: "ANCILLARY_SURGE_FEE",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 6800,
        message: "",
        title: "Delivery Charge",
        amount: "6800",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID:
        "cid=7468015~p=2~eid=00000189-8df9-381d-0462-7619000d0257~srvts=1690304067613~80462",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "7.3 kms",
      hasSurge: false,
      cta: {
        link: "swiggy://menu?restaurant_id=592569&source=collection&query=Momos",
        type: "DEEPLINK",
        text: "RESTAURANT_MENU",
      },
      sla: {
        restaurantId: "",
        deliveryTime: 32,
        minDeliveryTime: 32,
        maxDeliveryTime: 32,
        lastMileTravel: 0,
        lastMileDistance: 7.3,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "4.0",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    info: {
      type: "F",
      id: "623342",
      name: "Aho Punjab By Terra Food Co.",
      uuid: "9d492172-aa02-492c-9355-540f037db90e",
      city: "4",
      area: "Lajpat Nagar 1",
      totalRatingsString: "500+ ratings",
      cloudinaryImageId: "8299f95ac5f7bfd7db43dd8d46d21d21",
      cuisines: [
        "North Indian",
        "Thalis",
        "Biryani",
        "Kebabs",
        "Desserts",
        "Beverages",
        "Punjabi",
      ],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 34,
      minDeliveryTime: 34,
      maxDeliveryTime: 34,
      slaString: "34 MINS",
      lastMileTravel: 8.300000190734863,
      slugs: {
        restaurant: "aho-punjab-by-terra-food-co.-lajpat-nagar-lajpat-nagar",
        city: "delhi",
      },
      cityState: "4",
      address:
        "C-108 , GROUND FLOOR, LAJPAT NAGAR -1 , SAKET, South , Delhi-110024",
      locality: "Saket",
      parentId: 368424,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "distance",
            fee: 9900,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 9900,
        message: "",
        title: "Delivery Charge",
        amount: "9900",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "Closes soon",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID:
        "cid=7485378~p=1~eid=00000189-654c-91f0-179a-1cc100a60161~srvts=1689621664240",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "8.3 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "40% OFF",
        subHeader: "UPTO ₹80",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "623342",
        deliveryTime: 34,
        minDeliveryTime: 34,
        maxDeliveryTime: 34,
        lastMileTravel: 8.300000190734863,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "3.9",
      totalRatings: 500,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    info: {
      type: "F",
      id: "8614",
      name: "Burger King",
      uuid: "9e07cf51-cdce-4b03-a16d-9770829708b0",
      city: "4",
      area: "Connaught Place",
      totalRatingsString: "10000+ ratings",
      cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
      cuisines: ["Burgers", "American"],
      tags: [],
      costForTwo: 35000,
      costForTwoString: "₹350 FOR TWO",
      deliveryTime: 47,
      minDeliveryTime: 47,
      maxDeliveryTime: 47,
      slaString: "47 MINS",
      lastMileTravel: 1,
      slugs: {
        restaurant: "burger-king-inner-circle-connaught-place",
        city: "delhi",
      },
      cityState: "4",
      address: "E-8, Inner Circle, Connaught Place, New Delhi",
      locality: "E Block",
      parentId: 166,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3800,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3800,
        message: "",
        title: "Delivery Charge",
        amount: "3800",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "Closes soon",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "60% OFF",
        subHeader: "UPTO ₹120",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "8614",
        deliveryTime: 47,
        minDeliveryTime: 47,
        maxDeliveryTime: 47,
        lastMileTravel: 1,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.3",
      totalRatings: 10000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    info: {
      type: "F",
      id: "648524",
      name: "RollsKing",
      uuid: "dd9d214d-877b-4630-b238-e1cbc0fd2077",
      city: "4",
      area: "Connaught Place",
      totalRatingsString: "100+ ratings",
      cloudinaryImageId: "35662624fc589e6ab075b6af6dbb65d1",
      cuisines: ["North Indian", "Fast Food", "Beverages"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 28,
      minDeliveryTime: 28,
      maxDeliveryTime: 28,
      slaString: "28 MINS",
      lastMileTravel: 0.800000011920929,
      slugs: {
        restaurant: "rollsking-connaught-place-connaught-place",
        city: "delhi",
      },
      cityState: "4",
      address:
        "PROPERTY NO. L 1/3 & 1/4, GROUND FLOOR, BLOCK L, MIDDLE WING CIRCLE-D,CONNAUGHT CIRCUS, NEW DELHI 110001 ,CHANKYA PURI, New Delhi, Delhi-110001",
      locality: "Chankya puri",
      parentId: 4697,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "distance",
            fee: 3800,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3800,
        message: "",
        title: "Delivery Charge",
        amount: "3800",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "Closes soon",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.8 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "20% OFF",
        subHeader: "ABOVE ₹700",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "648524",
        deliveryTime: 28,
        minDeliveryTime: 28,
        maxDeliveryTime: 28,
        lastMileTravel: 0.800000011920929,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.0",
      totalRatings: 100,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    info: {
      type: "F",
      id: "328803",
      name: "Giani Ice Cream",
      uuid: "454b941c-3db8-4b8c-a85f-318460d1ed8a",
      city: "4",
      area: "Moti Bagh",
      totalRatingsString: "500+ ratings",
      cloudinaryImageId: "si2uenvjloiipqvqqg56",
      cuisines: ["Ice Cream", "Desserts"],
      tags: [],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 35,
      minDeliveryTime: 35,
      maxDeliveryTime: 35,
      slaString: "35 MINS",
      lastMileTravel: 9.399999618530273,
      slugs: {
        restaurant: "giani-south-campus-south-campus",
        city: "delhi",
      },
      cityState: "4",
      address: "Shop No 121, Nanakpura Market, RK Puram, South delhi",
      locality: "Nanakpura Market",
      parentId: 6577,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "distance",
            fee: 11400,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 11400,
        message: "",
        title: "Delivery Charge",
        amount: "11400",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "Closes soon",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID:
        "cid=7429560~p=4~eid=00000189-654c-91f0-179a-1cc200a60474~srvts=1689621664240",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "9.3 kms",
      hasSurge: false,
      sla: {
        restaurantId: "328803",
        deliveryTime: 35,
        minDeliveryTime: 35,
        maxDeliveryTime: 35,
        lastMileTravel: 9.399999618530273,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "4.3",
      totalRatings: 500,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    info: {
      type: "F",
      id: "85711",
      name: "Nirula's",
      uuid: "fed6c11f-7214-432f-9c0b-1516f11ada6b",
      city: "4",
      area: "Connaught Place",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "94c82b9d46792c198fff64899ff05bd2",
      cuisines: [
        "Pizzas",
        "Burgers",
        "Ice Cream",
        "North Indian",
        "Fast Food",
        "Pastas",
        "Beverages",
      ],
      tags: [],
      costForTwo: 50000,
      costForTwoString: "₹500 FOR TWO",
      deliveryTime: 27,
      minDeliveryTime: 27,
      maxDeliveryTime: 27,
      slaString: "27 MINS",
      lastMileTravel: 0.800000011920929,
      slugs: {
        restaurant: "nirulas-m-block-connaught-place",
        city: "delhi",
      },
      cityState: "4",
      address:
        "57, M Block, Middle Circle, Connaught Place, Near Rajiv Chowk, Metro Gate No. 4, Shankar Market, Block M, Connaught Place, New Delhi, Delhi 110001",
      locality: "M Block",
      parentId: 1738,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "distance",
            fee: 3800,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3800,
        message: "",
        title: "Delivery Charge",
        amount: "3800",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.8 kms",
      hasSurge: false,
      sla: {
        restaurantId: "85711",
        deliveryTime: 27,
        minDeliveryTime: 27,
        maxDeliveryTime: 27,
        lastMileTravel: 0.800000011920929,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.3",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    info: {
      type: "F",
      id: "433575",
      name: "Ghee and Turmeric",
      uuid: "ee110f24-1e30-4d10-81d4-5ea7526dc90d",
      city: "4",
      area: "Connaught Place",
      totalRatingsString: "100+ ratings",
      cloudinaryImageId: "ufjount2ougtrytczkr1",
      cuisines: [
        "North Indian",
        "Tandoor",
        "Punjabi",
        "Beverages",
        "Desserts",
        "Mughlai",
      ],
      tags: [],
      costForTwo: 50000,
      costForTwoString: "₹500 FOR TWO",
      deliveryTime: 40,
      minDeliveryTime: 40,
      maxDeliveryTime: 40,
      slaString: "40 MINS",
      lastMileTravel: 0.4000000059604645,
      slugs: {
        restaurant:
          "ghee-and-turmeric-connaught-place-2-m-block-connaught-place",
        city: "delhi",
      },
      cityState: "4",
      address:
        "Plot No 3, M 66, First Floor, M Block, Connaught Place,, New Delhi, Delhi 110001",
      locality: "M Block",
      parentId: 261287,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3800,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3800,
        message: "",
        title: "Delivery Charge",
        amount: "3800",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "Closes soon",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.4 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "50% OFF",
        subHeader: "UPTO ₹100",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "433575",
        deliveryTime: 40,
        minDeliveryTime: 40,
        maxDeliveryTime: 40,
        lastMileTravel: 0.4000000059604645,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.1",
      totalRatings: 100,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    info: {
      type: "F",
      id: "332882",
      name: "Kwality Walls Frozen Dessert and Ice Cream Shop",
      uuid: "c345ed64-5600-4d59-9f1d-2f3f2bbd7039",
      city: "4",
      area: "Safdarjung",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "xhrxoybfrhbfhsid0mng",
      cuisines: ["Desserts", "Ice Cream", "Ice Cream Cakes"],
      tags: [],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 28,
      minDeliveryTime: 28,
      maxDeliveryTime: 28,
      slaString: "28 MINS",
      lastMileTravel: 9.5,
      slugs: {
        restaurant:
          "kwality-walls-frozen-dessert-and-ice-cream-shop-hauz-khas-hauz-khas",
        city: "delhi",
      },
      cityState: "4",
      address:
        "H-no 32-B, Ground floor, Arjun Nagar, Safdarjung Enclave, New Delhi , SAKET, South , Delhi, 110029",
      locality: "Hauz Khas",
      parentId: 582,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 10400,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 10400,
        message: "",
        title: "Delivery Charge",
        amount: "10400",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "Closes soon",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID:
        "cid=7505884~p=7~eid=00000189-654c-91f0-179a-1cc300a60715~srvts=1689621664240",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "9.5 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹150 OFF",
        subHeader: "ABOVE ₹349",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "332882",
        deliveryTime: 28,
        minDeliveryTime: 28,
        maxDeliveryTime: 28,
        lastMileTravel: 9.5,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "4.6",
      totalRatings: 1000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    info: {
      type: "F",
      id: "463875",
      name: "High on desserts",
      uuid: "f385a1ed-338b-415f-b592-c847c203be1e",
      city: "4",
      area: "Connaught Place",
      totalRatingsString: "500+ ratings",
      cloudinaryImageId: "qnd3xwzsablhcd5wq1gs",
      cuisines: ["Desserts", "Beverages", "Ice Cream", "Cafe"],
      tags: [],
      costForTwo: 12000,
      costForTwoString: "₹120 FOR TWO",
      deliveryTime: 24,
      minDeliveryTime: 24,
      maxDeliveryTime: 24,
      slaString: "24 MINS",
      lastMileTravel: 0.800000011920929,
      slugs: {
        restaurant: "high-on-desserts-connaught-place-connaught-place",
        city: "delhi",
      },
      cityState: "4",
      address:
        "Shop No. 80 , Municipal Market , Connaught Place, New Delhi-110001",
      locality: "L Block",
      parentId: 15221,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "distance",
            fee: 3800,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3800,
        message: "",
        title: "Delivery Charge",
        amount: "3800",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.8 kms",
      hasSurge: false,
      sla: {
        restaurantId: "463875",
        deliveryTime: 24,
        minDeliveryTime: 24,
        maxDeliveryTime: 24,
        lastMileTravel: 0.800000011920929,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.3",
      totalRatings: 500,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    info: {
      type: "F",
      id: "8620",
      name: "Biryani Blues",
      uuid: "38c2e533-f37f-4d2a-910e-08fdc3d4bfb0",
      city: "4",
      area: "Connaught Place",
      totalRatingsString: "10000+ ratings",
      cloudinaryImageId: "fyiito5fcwqiivggupdy",
      cuisines: [
        "Biryani",
        "Hyderabadi",
        "Lucknowi",
        "Kebabs",
        "Desserts",
        "Beverages",
      ],
      tags: [],
      costForTwo: 40000,
      costForTwoString: "₹400 FOR TWO",
      deliveryTime: 36,
      minDeliveryTime: 36,
      maxDeliveryTime: 36,
      slaString: "36 MINS",
      lastMileTravel: 1.100000023841858,
      slugs: {
        restaurant: "biryani-blues-scindia-house-connaught-place",
        city: "delhi",
      },
      cityState: "4",
      address:
        "Showroom 9, Scindia House, Connaught Circus, Connaught Place, New Delhi",
      locality: "N Block",
      parentId: 13813,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "distance",
            fee: 3800,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3800,
        message: "",
        title: "Delivery Charge",
        amount: "3800",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1.1 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹125 OFF",
        subHeader: "ABOVE ₹249",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "8620",
        deliveryTime: 36,
        minDeliveryTime: 36,
        maxDeliveryTime: 36,
        lastMileTravel: 1.100000023841858,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.2",
      totalRatings: 10000,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    info: {
      type: "F",
      id: "730743",
      name: "Hello Chatoro 91",
      uuid: "2e97640d-95a4-409a-95ad-49e61d1e0b0c",
      city: "4",
      area: "Mayur Vihar",
      totalRatingsString: "Too Few Ratings",
      cloudinaryImageId: "dd519572ed1bed19de47e94186e743ea",
      cuisines: ["North Indian"],
      tags: [],
      costForTwo: 25000,
      costForTwoString: "₹250 FOR TWO",
      deliveryTime: 39,
      minDeliveryTime: 39,
      maxDeliveryTime: 39,
      slaString: "39 MINS",
      lastMileTravel: 8.899999618530273,
      slugs: {
        restaurant: "hello-chatoro-91-mayur-vihar-mayur-vihar",
        city: "delhi",
      },
      cityState: "4",
      address:
        "222, Peer wali Galli, Adarsh Mohalla, Patparganj, Mayur Vihar, New Delhi, Delhi 110092, India",
      locality: "Peer wali Galli",
      parentId: 434163,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: "PROMOTED",
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 9900,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 9900,
        message: "",
        title: "Delivery Charge",
        amount: "9900",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID:
        "cid=7403703~p=10~eid=00000189-654c-91f0-179a-1cc400a60a5a~srvts=1689621664240",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "8.8 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "20% OFF",
        subHeader: "UPTO ₹50",
        discountTag: "",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "730743",
        deliveryTime: 39,
        minDeliveryTime: 39,
        maxDeliveryTime: 39,
        lastMileTravel: 8.899999618530273,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: true,
      avgRating: "--",
      totalRatings: 0,
      new: true,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    info: {
      type: "F",
      id: "554643",
      name: "Third Wave Coffee",
      uuid: "4739b95a-a34c-487c-8b86-fc4be13b37f4",
      city: "4",
      area: "Connaught Place",
      totalRatingsString: "500+ ratings",
      cloudinaryImageId: "d96267738c19ec62acb5390e52faba41",
      cuisines: ["Beverages", "Pizzas"],
      tags: [],
      costForTwo: 40000,
      costForTwoString: "₹400 FOR TWO",
      deliveryTime: 26,
      minDeliveryTime: 26,
      maxDeliveryTime: 26,
      slaString: "26 MINS",
      lastMileTravel: 0.699999988079071,
      slugs: {
        restaurant:
          "third-wave-coffee-roasters-connaught-place-connaught-place",
        city: "delhi",
      },
      cityState: "4",
      address:
        "E Block, E11, Mezzanine Floor, Connaught Place, New Delhi, Delhi 110086",
      locality: "E Block",
      parentId: 274773,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "distance",
            fee: 3800,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3800,
        message: "",
        title: "Delivery Charge",
        amount: "3800",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "Closes soon",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.6 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "₹100 OFF",
        subHeader: "ABOVE ₹599",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "554643",
        deliveryTime: 26,
        minDeliveryTime: 26,
        maxDeliveryTime: 26,
        lastMileTravel: 0.699999988079071,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.3",
      totalRatings: 500,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    info: {
      type: "F",
      id: "438612",
      name: "Baskin Robbins - Ice Cream Desserts",
      uuid: "43cf7e84-3c7b-4a0f-b894-51499bb7ca65",
      city: "4",
      area: "Chanakyapuri",
      totalRatingsString: "100+ ratings",
      cloudinaryImageId: "85ccae4e3576f9330af102c46ca85395",
      cuisines: ["Desserts", "Ice Cream"],
      tags: [],
      costForTwo: 25000,
      costForTwoString: "₹250 FOR TWO",
      deliveryTime: 28,
      minDeliveryTime: 28,
      maxDeliveryTime: 28,
      slaString: "28 MINS",
      lastMileTravel: 0.800000011920929,
      slugs: {
        restaurant: "baskin-robbins-chankya-puri-connaught-place",
        city: "delhi",
      },
      cityState: "4",
      address: "L-12 Cannought Circus,CHANKYA PURI, New Delhi, Delhi, 110001",
      locality: "Cannought Circus",
      parentId: 5588,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "distance",
            fee: 3800,
            message: "",
          },
          {
            name: "time",
            fee: 0,
            message: "",
          },
          {
            name: "special",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3800,
        message: "",
        title: "Delivery Charge",
        amount: "3800",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "0.8 kms",
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: "10% OFF",
        subHeader: "ABOVE ₹1000",
        discountTag: "FLAT DEAL",
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: "438612",
        deliveryTime: 28,
        minDeliveryTime: 28,
        maxDeliveryTime: 28,
        lastMileTravel: 0.800000011920929,
        lastMileDistance: 0,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        longDistance: "NOT_LONG_DISTANCE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.5",
      totalRatings: 100,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    info: {
      type: "F",
      id: "68693",
      name: "M Gopinath",
      uuid: "5fc5a3a7-462b-458d-a63e-2a990af21975",
      city: "4",
      area: "Rajinder Nagar",
      totalRatingsString: "",
      cloudinaryImageId: "eddz366enw6gpt3nysrt",
      cuisines: ["South Indian", "Chinese"],
      tags: [],
      costForTwo: 25000,
      costForTwoString: "₹250 FOR TWO",
      deliveryTime: 28,
      minDeliveryTime: 28,
      maxDeliveryTime: 28,
      slaString: "28 MINS",
      lastMileTravel: 0,
      slugs: {
        restaurant: "m-gopinath-old-rajinder-nagar-karol-bagh",
        city: "Delhi",
      },
      cityState: "4",
      address: "",
      locality: "Old Rajinder Nagar",
      parentId: 15817,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      aggregatedDiscountInfoV2: {
        header: "",
        shortDescriptionList: [],
        descriptionList: [],
        subHeader: "",
        headerType: 0,
        superFreedel: "",
      },
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "BASE_DISTANCE",
            fee: 5200,
            message: "",
          },
          {
            name: "BASE_TIME",
            fee: 0,
            message: "",
          },
          {
            name: "ANCILLARY_SURGE_FEE",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 5200,
        message: "",
        title: "Delivery Charge",
        amount: "5200",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [
          {
            iconId: "guiltfree/GF_Logo_android_3x",
            description: "",
            shortDescription: "options available",
            fontColor: "#7E808C",
          },
        ],
      },
      lastMileTravelString: "5 kms",
      hasSurge: false,
      cta: {
        link: "swiggy://menu?restaurant_id=68693&source=collection&query=South%20Indian",
        type: "DEEPLINK",
        text: "RESTAURANT_MENU",
      },
      sla: {
        restaurantId: "",
        deliveryTime: 28,
        minDeliveryTime: 28,
        maxDeliveryTime: 28,
        lastMileTravel: 0,
        lastMileDistance: 5,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.0",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    info: {
      type: "F",
      id: "8621",
      name: "Sagar Ratna",
      uuid: "3e2ed43c-7645-44c5-a224-dc46c31156b1",
      city: "4",
      area: "Connaught Place",
      totalRatingsString: "",
      cloudinaryImageId: "xaucswudilbnevouxpbi",
      cuisines: ["South Indian", "North Indian", "Chinese", "Desserts"],
      tags: [],
      costForTwo: 60000,
      costForTwoString: "₹600 FOR TWO",
      deliveryTime: 20,
      minDeliveryTime: 20,
      maxDeliveryTime: 20,
      slaString: "20 MINS",
      lastMileTravel: 0,
      slugs: {
        restaurant: "sagar-ratna-outer-circle-connaught-place",
        city: "Delhi",
      },
      cityState: "4",
      address: "",
      locality: "K Block",
      parentId: 793,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: "BASE_DISTANCE",
            fee: 3600,
            message: "",
          },
          {
            name: "BASE_TIME",
            fee: 0,
            message: "",
          },
          {
            name: "ANCILLARY_SURGE_FEE",
            fee: 0,
            message: "",
          },
        ],
        totalFees: 3600,
        message: "",
        title: "Delivery Charge",
        amount: "3600",
        icon: "",
      },
      availability: {
        opened: true,
        nextOpenMessage: "",
        nextCloseMessage: "",
      },
      longDistanceEnabled: 0,
      rainMode: "NONE",
      thirdPartyAddress: false,
      thirdPartyVendor: "",
      adTrackingID: "",
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: "1 kms",
      hasSurge: false,
      cta: {
        link: "swiggy://menu?restaurant_id=8621&source=collection&query=South%20Indian",
        type: "DEEPLINK",
        text: "RESTAURANT_MENU",
      },
      sla: {
        restaurantId: "",
        deliveryTime: 20,
        minDeliveryTime: 20,
        maxDeliveryTime: 20,
        lastMileTravel: 0,
        lastMileDistance: 1,
        serviceability: "SERVICEABLE",
        rainMode: "NONE",
        preferentialService: false,
        iconType: "EMPTY",
      },
      promoted: false,
      avgRating: "4.3",
      totalRatings: 0,
      new: false,
    },
    subtype: "basic",
  },
];
